name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  abi-up-to-date:
    name: Check ABI files are up-to-date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: ensure `./wit/deps` are in sync
      run: |
        curl -Lo 'wit-deps' https://github.com/bytecodealliance/wit-deps/releases/download/v0.5.0/wit-deps-x86_64-unknown-linux-musl
        chmod +x wit-deps
        ./wit-deps lock
        ./wit-deps -m wit-0.3.0-draft/deps.toml -l wit-0.3.0-draft/deps.lock -d wit-0.3.0-draft/deps lock
        git add -N wit/deps
        git add -N wit-0.3.0-draft/deps
        git diff --exit-code
    - uses: WebAssembly/wit-abi-up-to-date@v24
      with:
        all-features: 'true'
